### ISSUE TITLE
Поправить кнопку открытия попапа  edit-feetback

### ISSUE THREAD

**Issue by nikcosmos** [ReinmandTrial/kart#18]
![image](https://github.com/ReinmandTrial/kart/assets/95741551/97c79754-91c4-4a33-b5b9-b0a793e49586)

- [x] Проверить ее на ПК 
- [x] Проверить ее на Мобилке
- [x] Сделать ее через тег button, если это не так + добавить type = 'button'

Аттрибуте type нужно добавлять обязательно к кнопкам, либо к кликабельным div
Так же помни что тег button - это строчный элемент внутри него нельзя использовать div,p... либо другие блочные элементы, можно использовать только строчные например span - это ошибка с точки зрения семантики

**Comment by Kozzzlova** [comment]
с кнопкой проблем нет
